
/*
 * This file was generated by the SOM Compiler.
 * FileName: HWITER.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.2
 *     SOM Emitter emith: 2.41
 */

#ifndef SOM_HWITer_h
#define SOM_HWITer_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef HWITer
#define HWITer SOMObject
#endif
#include <wpabs.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef M_HWITer
    #define M_HWITer SOMObject
#endif /* M_HWITer */

/*
 * End of user-defined types.
 */

#define HWITer_MajorVersion 1
#define HWITer_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define HWITerNewClass hwiterc
#pragma linkage(hwiterc, system)
#define HWITerClassData hwiterd
#define HWITerCClassData hwiterx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <HWITER.h>
/*--------------Migration------------*/
#define HWITer_classObj HWITerClassData.classObject
#define _HWITer HWITer_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK HWITerNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(HWITerNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct HWITerClassDataStructure {
	SOMAny *classObject;
	somMToken checkDateTime;
	somMToken DeskMan2QuerySetup;
} SOMDLINK HWITerClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct HWITerCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK HWITerCClassData;

/*
 * New and Renew macros for HWITer
 */
#define HWITerNew() \
   (_somNew(_HWITer ? _HWITer : HWITerNewClass(HWITer_MajorVersion, HWITer_MinorVersion)))
#define HWITerRenew(buf) \
   (_somRenew(_HWITer ? _HWITer : HWITerNewClass(HWITer_MajorVersion, HWITer_MinorVersion), buf))

/*
 * Override method: wpAddSettingsPages
 */
#define HWITer_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpFormatDragItem
 */
#define HWITer_wpFormatDragItem(somSelf,pdrgItem) \
	WPObject_wpFormatDragItem(somSelf,pdrgItem)

/*
 * Override method: wpInitData
 */
#define HWITer_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpRestoreState
 */
#define HWITer_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpSaveState
 */
#define HWITer_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpSetup
 */
#define HWITer_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * New Method: checkDateTime
 */
typedef BOOL   SOMLINK somTP_HWITer_checkDateTime(HWITer *somSelf);
#pragma linkage(somTP_HWITer_checkDateTime, system)
typedef somTP_HWITer_checkDateTime *somTD_HWITer_checkDateTime;
#define somMD_HWITer_checkDateTime "::HWITer::checkDateTime"
#define HWITer_checkDateTime(somSelf) \
    (SOM_Resolve(somSelf, HWITer, checkDateTime) \
	(somSelf))
#ifndef SOMGD_checkDateTime
    #if (defined(_checkDateTime) || defined(__checkDateTime))
        #undef _checkDateTime
        #undef __checkDateTime
        #define SOMGD_checkDateTime 1
    #else
        #define _checkDateTime HWITer_checkDateTime
    #endif /* _checkDateTime */
#endif /* SOMGD_checkDateTime */

/*
 * New Method: DeskMan2QuerySetup
 */
typedef APIRET   SOMLINK somTP_HWITer_DeskMan2QuerySetup(HWITer *somSelf,
		WPObject* setupObject);
#pragma linkage(somTP_HWITer_DeskMan2QuerySetup, system)
typedef somTP_HWITer_DeskMan2QuerySetup *somTD_HWITer_DeskMan2QuerySetup;
#define somMD_HWITer_DeskMan2QuerySetup "::HWITer::DeskMan2QuerySetup"
#define HWITer_DeskMan2QuerySetup(somSelf,setupObject) \
    (SOM_Resolve(somSelf, HWITer, DeskMan2QuerySetup) \
	(somSelf,setupObject))
#ifndef SOMGD_DeskMan2QuerySetup
    #if (defined(_DeskMan2QuerySetup) || defined(__DeskMan2QuerySetup))
        #undef _DeskMan2QuerySetup
        #undef __DeskMan2QuerySetup
        #define SOMGD_DeskMan2QuerySetup 1
    #else
        #define _DeskMan2QuerySetup HWITer_DeskMan2QuerySetup
    #endif /* _DeskMan2QuerySetup */
#endif /* SOMGD_DeskMan2QuerySetup */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define HWITer_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define HWITer_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define HWITer_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define HWITer_wpAddToObjUseList WPObject_wpAddToObjUseList
#define HWITer_wpAllocMem WPObject_wpAllocMem
#define HWITer_wpAppendObject WPObject_wpAppendObject
#define HWITer_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define HWITer_wpClose WPObject_wpClose
#define HWITer_wpCnrInsertObject WPObject_wpCnrInsertObject
#define HWITer_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define HWITer_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define HWITer_wpConfirmDelete WPObject_wpConfirmDelete
#define HWITer_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define HWITer_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define HWITer_wpCopyObject WPObject_wpCopyObject
#define HWITer_wpCreateAnother WPObject_wpCreateAnother
#define HWITer_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define HWITer_wpCreateShadowObject WPObject_wpCreateShadowObject
#define HWITer_wpDelete WPObject_wpDelete
#define HWITer_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define HWITer_wpDisplayHelp WPObject_wpDisplayHelp
#define HWITer_wpDisplayMenu WPObject_wpDisplayMenu
#define HWITer_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define HWITer_wpDraggedOverObject WPObject_wpDraggedOverObject
#define HWITer_wpDragOver WPObject_wpDragOver
#define HWITer_wpDrop WPObject_wpDrop
#define HWITer_wpDroppedOnObject WPObject_wpDroppedOnObject
#define HWITer_wpEndConversation WPObject_wpEndConversation
#define HWITer_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define HWITer_wpFindUseItem WPObject_wpFindUseItem
#define HWITer_wpFree WPObject_wpFree
#define HWITer_wpFreeMem WPObject_wpFreeMem
#define HWITer_wpHide WPObject_wpHide
#define HWITer_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define HWITer_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define HWITer_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define HWITer_wpMenuItemSelected WPObject_wpMenuItemSelected
#define HWITer_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define HWITer_wpMoveObject WPObject_wpMoveObject
#define HWITer_wpOpen WPObject_wpOpen
#define HWITer_wpPrintObject WPObject_wpPrintObject
#define HWITer_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define HWITer_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define HWITer_wpQueryConfirmations WPObject_wpQueryConfirmations
#define HWITer_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define HWITer_wpQueryDefaultView WPObject_wpQueryDefaultView
#define HWITer_wpQueryDetailsData WPObject_wpQueryDetailsData
#define HWITer_wpQueryError WPObject_wpQueryError
#define HWITer_wpSetFolder WPObject_wpSetFolder
#define HWITer_wpQueryFolder WPObject_wpQueryFolder
#define HWITer_wpQueryIcon WPObject_wpQueryIcon
#define HWITer_wpQueryIconData WPObject_wpQueryIconData
#define HWITer_wpQueryMinWindow WPObject_wpQueryMinWindow
#define HWITer_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define HWITer_wpQueryStyle WPObject_wpQueryStyle
#define HWITer_wpSetTaskRec WPObject_wpSetTaskRec
#define HWITer_wpFindTaskRec WPObject_wpFindTaskRec
#define HWITer_wpQueryTitle WPObject_wpQueryTitle
#define HWITer_wpRegisterView WPObject_wpRegisterView
#define HWITer_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define HWITer_wpRender WPObject_wpRender
#define HWITer_wpRenderComplete WPObject_wpRenderComplete
#define HWITer_wpReplaceObject WPObject_wpReplaceObject
#define HWITer_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define HWITer_wpRestore WPObject_wpRestore
#define HWITer_wpRestoreData WPObject_wpRestoreData
#define HWITer_wpRestoreLong WPObject_wpRestoreLong
#define HWITer_wpRestoreString WPObject_wpRestoreString
#define HWITer_wpSaveData WPObject_wpSaveData
#define HWITer_wpSaveImmediate WPObject_wpSaveImmediate
#define HWITer_wpSaveDeferred WPObject_wpSaveDeferred
#define HWITer_wpSaveLong WPObject_wpSaveLong
#define HWITer_wpSaveString WPObject_wpSaveString
#define HWITer_wpScanSetupString WPObject_wpScanSetupString
#define HWITer_wpSetConcurrentView WPObject_wpSetConcurrentView
#define HWITer_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define HWITer_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define HWITer_wpSetDefaultView WPObject_wpSetDefaultView
#define HWITer_wpSetError WPObject_wpSetError
#define HWITer_wpSetIconHandle WPObject_wpSetIconHandle
#define HWITer_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define HWITer_wpSetupOnce WPObject_wpSetupOnce
#define HWITer_wpSetIcon WPObject_wpSetIcon
#define HWITer_wpSetIconData WPObject_wpSetIconData
#define HWITer_wpSetMinWindow WPObject_wpSetMinWindow
#define HWITer_wpSetStyle WPObject_wpSetStyle
#define HWITer_wpModifyStyle WPObject_wpModifyStyle
#define HWITer_wpSetTitle WPObject_wpSetTitle
#define HWITer_wpSwitchTo WPObject_wpSwitchTo
#define HWITer_wpUnInitData WPObject_wpUnInitData
#define HWITer_wpViewObject WPObject_wpViewObject
#define HWITer_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define HWITer_wpQueryHandle WPObject_wpQueryHandle
#define HWITer_wpUnlockObject WPObject_wpUnlockObject
#define HWITer_wpObjectReady WPObject_wpObjectReady
#define HWITer_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define HWITer_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define HWITer_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define HWITer_wpIsDeleteable WPObject_wpIsDeleteable
#define HWITer_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define HWITer_wpSetObjectID WPObject_wpSetObjectID
#define HWITer_wpQueryObjectID WPObject_wpQueryObjectID
#define HWITer_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define HWITer_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define HWITer_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define HWITer_wpFindViewItem WPObject_wpFindViewItem
#define HWITer_wpLockObject WPObject_wpLockObject
#define HWITer_wpIsLocked WPObject_wpIsLocked
#define HWITer_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define HWITer_wpWaitForClose WPObject_wpWaitForClose
#define HWITer_somDefaultInit SOMObject_somDefaultInit
#define HWITer_somDestruct SOMObject_somDestruct
#define HWITer_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define HWITer_somDefaultAssign SOMObject_somDefaultAssign
#define HWITer_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define HWITer_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define HWITer_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define HWITer_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define HWITer_somDefaultVAssign SOMObject_somDefaultVAssign
#define HWITer_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define HWITer_somInit SOMObject_somInit
#define HWITer_somFree SOMObject_somFree
#define HWITer_somUninit SOMObject_somUninit
#define HWITer_somGetClass SOMObject_somGetClass
#define HWITer_somGetClassName SOMObject_somGetClassName
#define HWITer_somGetSize SOMObject_somGetSize
#define HWITer_somIsA SOMObject_somIsA
#define HWITer_somIsInstanceOf SOMObject_somIsInstanceOf
#define HWITer_somRespondsTo SOMObject_somRespondsTo
#define HWITer_somDispatch SOMObject_somDispatch
#define HWITer_somClassDispatch SOMObject_somClassDispatch
#define HWITer_somCastObj SOMObject_somCastObj
#define HWITer_somResetObj SOMObject_somResetObj
#define HWITer_somDispatchV SOMObject_somDispatchV
#define HWITer_somDispatchL SOMObject_somDispatchL
#define HWITer_somDispatchA SOMObject_somDispatchA
#define HWITer_somDispatchD SOMObject_somDispatchD
#define HWITer_somPrintSelf SOMObject_somPrintSelf
#define HWITer_somDumpSelf SOMObject_somDumpSelf
#define HWITer_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_HWITer_h */

#ifndef SOM_M_HWITer_h
#define SOM_M_HWITer_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_HWITer
#define M_HWITer SOMObject
#endif
#include <wpabs.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_HWITer_MajorVersion 1
#define M_HWITer_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_HWITerNewClass hwiterc
#pragma linkage(hwiterc, system)
#define M_HWITerClassData hwiterd
#define M_HWITerCClassData hwiterx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_HWITer_classObj M_HWITerClassData.classObject
#define _M_HWITer M_HWITer_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_HWITerNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_HWITerNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_HWITerClassDataStructure {
	SOMAny *classObject;
	somMToken clsQueryHmod;
} SOMDLINK M_HWITerClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_HWITerCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_HWITerCClassData;

/*
 * New and Renew macros for M_HWITer
 */
#define M_HWITerNew() \
   (_somNew(_M_HWITer ? _M_HWITer : M_HWITerNewClass(M_HWITer_MajorVersion, M_HWITer_MinorVersion)))
#define M_HWITerRenew(buf) \
   (_somRenew(_M_HWITer ? _M_HWITer : M_HWITerNewClass(M_HWITer_MajorVersion, M_HWITer_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_HWITer_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_HWITer_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_HWITer_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryTitle
 */
#define M_HWITer_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_HWITer_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * New Method: clsQueryHmod
 */
typedef HMODULE   SOMLINK somTP_M_HWITer_clsQueryHmod(M_HWITer *somSelf);
#pragma linkage(somTP_M_HWITer_clsQueryHmod, system)
typedef somTP_M_HWITer_clsQueryHmod *somTD_M_HWITer_clsQueryHmod;
#define somMD_M_HWITer_clsQueryHmod "::M_HWITer::clsQueryHmod"
#define M_HWITer_clsQueryHmod(somSelf) \
    (SOM_Resolve(somSelf, M_HWITer, clsQueryHmod) \
	(somSelf))
#ifndef SOMGD_clsQueryHmod
    #if (defined(_clsQueryHmod) || defined(__clsQueryHmod))
        #undef _clsQueryHmod
        #undef __clsQueryHmod
        #define SOMGD_clsQueryHmod 1
    #else
        #define _clsQueryHmod M_HWITer_clsQueryHmod
    #endif /* _clsQueryHmod */
#endif /* SOMGD_clsQueryHmod */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_HWITer_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_HWITer_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_HWITer_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_HWITer_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_HWITer_wpclsNew M_WPObject_wpclsNew
#define M_HWITer_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_HWITer_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_HWITer_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_HWITer_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_HWITer_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_HWITer_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_HWITer_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_HWITer_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_HWITer_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_HWITer_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_HWITer_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_HWITer_wpclsSetError M_WPObject_wpclsSetError
#define M_HWITer_wpclsQueryError M_WPObject_wpclsQueryError
#define M_HWITer_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_HWITer_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_HWITer_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_HWITer_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_HWITer_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_HWITer_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_HWITer_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_HWITer_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_HWITer_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_HWITer_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_HWITer_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_HWITer_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_HWITer__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_HWITer__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_HWITer__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_HWITer__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_HWITer_somNew SOMClass_somNew
#define M_HWITer_somNewNoInit SOMClass_somNewNoInit
#define M_HWITer_somRenew SOMClass_somRenew
#define M_HWITer_somRenewNoInit SOMClass_somRenewNoInit
#define M_HWITer_somRenewNoZero SOMClass_somRenewNoZero
#define M_HWITer_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_HWITer_somAllocate SOMClass_somAllocate
#define M_HWITer_somDeallocate SOMClass_somDeallocate
#define M_HWITer__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_HWITer__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_HWITer_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_HWITer_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_HWITer_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_HWITer_somInitClass SOMClass_somInitClass
#define M_HWITer_somInitMIClass SOMClass_somInitMIClass
#define M_HWITer_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_HWITer_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_HWITer_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_HWITer_somClassReady SOMClass_somClassReady
#define M_HWITer_somGetApplyStub SOMClass_somGetApplyStub
#define M_HWITer_somGetClassData SOMClass_somGetClassData
#define M_HWITer_somSetClassData SOMClass_somSetClassData
#define M_HWITer_somGetClassMtab SOMClass_somGetClassMtab
#define M_HWITer_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_HWITer_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_HWITer_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_HWITer_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_HWITer_somGetMemberToken SOMClass_somGetMemberToken
#define M_HWITer_somGetMethodData SOMClass_somGetMethodData
#define M_HWITer_somGetRdStub SOMClass_somGetRdStub
#define M_HWITer_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_HWITer_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_HWITer_somGetMethodToken SOMClass_somGetMethodToken
#define M_HWITer_somGetName SOMClass_somGetName
#define M_HWITer_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_HWITer_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_HWITer_somGetNumMethods SOMClass_somGetNumMethods
#define M_HWITer_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_HWITer_somGetParent SOMClass_somGetParent
#define M_HWITer_somGetParents SOMClass_somGetParents
#define M_HWITer_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_HWITer_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_HWITer_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_HWITer_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_HWITer_somFindMethod SOMClass_somFindMethod
#define M_HWITer_somFindMethodOk SOMClass_somFindMethodOk
#define M_HWITer_somFindSMethod SOMClass_somFindSMethod
#define M_HWITer_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_HWITer_somLookupMethod SOMClass_somLookupMethod
#define M_HWITer_somCheckVersion SOMClass_somCheckVersion
#define M_HWITer_somDescendedFrom SOMClass_somDescendedFrom
#define M_HWITer_somSupportsMethod SOMClass_somSupportsMethod
#define M_HWITer_somDefinedMethod SOMClass_somDefinedMethod
#define M_HWITer_somOverrideMtab SOMClass_somOverrideMtab
#define M_HWITer_somDefaultInit SOMObject_somDefaultInit
#define M_HWITer_somDestruct SOMObject_somDestruct
#define M_HWITer_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_HWITer_somDefaultAssign SOMObject_somDefaultAssign
#define M_HWITer_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_HWITer_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_HWITer_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_HWITer_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_HWITer_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_HWITer_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_HWITer_somInit SOMObject_somInit
#define M_HWITer_somFree SOMObject_somFree
#define M_HWITer_somUninit SOMObject_somUninit
#define M_HWITer_somGetClass SOMObject_somGetClass
#define M_HWITer_somGetClassName SOMObject_somGetClassName
#define M_HWITer_somGetSize SOMObject_somGetSize
#define M_HWITer_somIsA SOMObject_somIsA
#define M_HWITer_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_HWITer_somRespondsTo SOMObject_somRespondsTo
#define M_HWITer_somDispatch SOMObject_somDispatch
#define M_HWITer_somClassDispatch SOMObject_somClassDispatch
#define M_HWITer_somCastObj SOMObject_somCastObj
#define M_HWITer_somResetObj SOMObject_somResetObj
#define M_HWITer_somDispatchV SOMObject_somDispatchV
#define M_HWITer_somDispatchL SOMObject_somDispatchL
#define M_HWITer_somDispatchA SOMObject_somDispatchA
#define M_HWITer_somDispatchD SOMObject_somDispatchD
#define M_HWITer_somPrintSelf SOMObject_somPrintSelf
#define M_HWITer_somDumpSelf SOMObject_somDumpSelf
#define M_HWITer_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_HWITer_h */
